### PR TITLE
Adapt-Plugin and UPDATE_TEMPLATES.md updates

### PR DESCRIPTION
**Pull request by leamas**
UPDATE_TEMPLATES: updated form current sources.

Plugin-Adaptation: rewritten with a stronger focus on update-templates and overall workflow.

### CODE REVIEW

**Comment by leamas** [comment]
Added fix for https://github.com/Rasbats/shipdriver_pi/issues/364#issuecomment-997172292. See comment in 340ef20

**Comment by rgleason** [comment]
I strongly disagree about the documentation being adequate.

**Comment by leamas** [comment]
Well,. I guess you havn't really seen what is in this update?

**Comment by rgleason** [comment]
I've just been looking for this in the Shipdriver documentation and could not find it anywhere. Perhaps I can get to it from here.

**Comment by rgleason** [comment]
I need update instruction from SD 2.8.7.2 Template for Logbookkonni.

**Comment by leamas** [comment]
Let's  first handle https://github.com/Rasbats/shipdriver_pi/issues/364. One thing at a time.

**Comment by rgleason** [comment]
I am getting tired of that one. I worked on it for a day and it is pushed to plugins now. 
But if you insist, I will go back to it.

**Comment by leamas** [comment]
Do so. See you there. Limited bandwidth, though.

**Pull request merged**
