### PR TITLE
Usage: Update from current INSTALL.md

### PR DESCRIPTION
**Pull request by leamas**
- Drop  legacy package generation
- Add Android builds.

### CODE REVIEW

**Comment by Rasbats** [comment]
_ci/circleci-build-macos_ uses _build-osx_ not build. When did it change? Perhaps build would be better to keep the different OS in sync.

**Comment by leamas** [comment]
on phone.. No  "keeping i  sync" does not work when doing parallel builds, the different builds  collides when using the same directory.

However, when doing a manual, local build  using  _build_ is just fine

**Comment by Rasbats** [comment]
>However, when doing a manual, local build using build is just fine

You probably saw ... I amended the script comment in _ci/circleci-build-macos.sh_ so that when the script is used locally on the Mac the instruction is to `cd build-osx`.

**Comment by leamas** [comment]
nope, didn't see that. But great, this kind of polish is what we should try to do in this phase

Have PRs under way for open issues, but neither time nor computer. Later today, hopefully.

**Comment by leamas** [comment]
Updated to use build-osx i. e., rebased to current master.

Good catch!

**Pull request merged**
