### PR TITLE
Resurrect Github page, fixes (#39).

### PR DESCRIPTION
**Pull request by leamas**
Still more refactoring.

Resurrected the Github page and transformed it into "final checks and testing". The page contains a good, condensed checklist we IMHO should take care of.

Focusing on the actual implementation flow: First make it build locally, then proceed to CI services.

Move the scripts/ stuff to  a separate page marked as experimental.

Happy Xmas!

### CODE REVIEW

**Comment by Rasbats** [comment]
Bah humbug.

**Comment by leamas** [comment]
> Bah humbug.

?

**Comment by Rasbats** [comment]
Charles Dickens - A Christmas Carol - Scrooge

**Comment by leamas** [comment]
:)

**Pull request merged**
